---
title: Welkom op Antarctica
hero_image: images/banner.png
description: Gebruik CSS om een geweldige website te maken
version: 4
listed: true
copyedit: false
last_tested: '2021-03-26'
steps:
  - title: Inleiding
  - title: Maak een navigatiebalk
  - title: Een navigatiebalk vormgeven
    completion: engaged
  - title: Voeg hero-afbeeldingen toe
  - title: Rasters gebruiken
  - title: Animaties gebruiken
  - title: Verschillende soorten rasters
  - title: Responsieve navigatiebalk
  - title: Responsieve rasters
    completion: internal
  - title: Reflectie
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Verbeter je project