---
title: welcome-to-antarctica
hero_image: images/banner.png
description: Use CSS to make a great website
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Create a navbar
- title: Add hero images
- title: Using grids and animations
- title: Different types of grids
- title: Make it responsive
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Upgrade your project
- title: What next?
