---
title: Bienvenue en Antarctique 
hero_image: images/banner.png
description: Utilise CSS pour créer un site web génial
version: 4
listed: true
copyedit: false
last_tested: '2021-03-26'
steps:
  - 
    title: Introduction
  - 
    title: Créer une barre de navigation
  - 
    title: Styliser une barre de navigation
    completion: engaged
  - 
    title: Ajouter des images Hero
  - 
    title: Utiliser des grilles
  - 
    title: Utiliser des animations
  - 
    title: Différents types de grilles
  - 
    title: Barre de navigation réactive
  - 
    title: Grilles réactives
    completion: internal
  - 
    title: Réflexion
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Améliorer ton projet
